
services:
  # 1. Kafka Service
  kafka:
    image: ${KAFKA_IMAGE}
    container_name: kafka-kraft
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT}
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_NODE_ID}@localhost:${KAFKA_CONTROLLER_PORT}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_NUM_PARTITIONS=${KAFKA_NUM_PARTITIONS}
    volumes:
      - kafka_data:/var/lib/kafka/data

  # 2. Existing Video Service DB
  mysql-video:
    image: ${MYSQL_IMAGE}
    container_name: mysql-video-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_VIDEO}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_VIDEO_EXTERNAL_PORT}:3306" # External 3307 maps to internal 3306
    volumes:
      - video_db_data:/var/lib/mysql

  # 3. NEW Category Service DB
  mysql-category:
    image: ${MYSQL_IMAGE}
    container_name: mysql-category-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_CATEGORY}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_CATEGORY_EXTERNAL_PORT}:3306" # External 3308 maps to internal 3306
    volumes:
      - category_db_data:/var/lib/mysql

  # 4. Redis Service for Category
  # The Leader
  redis-master:
    image: ${REDIS_IMAGE}
    container_name: redis-master
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "8001:8001" #Redis Insight Dashboard
    volumes:
      - redis_data:/data

  # The Follower (high Availablity)
  redis-replica:
    image: ${REDIS_IMAGE}
    container_name: redis-replica
    environment: 
     REDIS_ARGS: "--replicaof redis-master ${REDIS_PORT}"
    depends_on:
     - redis-master

  # The Watcher (Sentinel)
  redis-sentinel:
    image: ${REDIS_SENTINEL_IMAGE}
    container_name: redis-sentinel
    environment:
     - REDIS_MASTER_HOST=redis-master
    ports:
     - "${REDIS_SENTINEL_PORT}:${REDIS_SENTINEL_PORT}"
    depends_on:
     - redis-master
     - redis-replica

  # 5. ElasticSearxh service
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}" 
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status.*green\\|status.*yellow'"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    
volumes:
  kafka_data:
    driver: local
  video_db_data:    
    driver: local
  category_db_data:
    driver: local
  redis_data:
    driver: local
  es_data:
    driver: local